# Generated by Django 5.0.1 on 2024-02-08 04:54

import firstapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('num', models.IntegerField(validators=[firstapp.models.int_is_even])),
            ],
        ),
    ]
